### ISSUE TITLE
Ruby: some keywords are highlighted pink

### ISSUE THREAD

**Issue by calebmeyer** [gristel/duotint-slime-syntax#2]
<img width="265" alt="screen shot 2016-03-23 at 4 16 11 pm" src="https://cloud.githubusercontent.com/assets/3342777/14001146/97aac0da-f112-11e5-9208-dfe78a0936cd.png">

The specific classes applied to these elements are `.keyword`, `.other`, and `.special-method` (as well as `.ruby`, of course)

**Comment by gristel** [comment]
Should be fixed in 0.3.4 release
